# Generated by Django 4.2.4 on 2023-10-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('middleName', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KrTest.image')),
            ],
        ),
    ]
