# Generated by Django 4.2.4 on 2023-10-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KrTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthDate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middleName',
            new_name='middlename',
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_path', to='KrTest.image'),
        ),
    ]
